version: "3.9"

services:
  database_ioasys:
    image: postgres
    container_name: database_ioasys
    restart: always
    ports: 
      - "65432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ioasys_final
    volumes:
      - pgdata:/data/postgres    


  app:
    build: .
    container_name: ioasys_ecommerce
    restart: always
    ports: 
      - 3000:3000      
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules
    links: 
      - database_ioasys
    depends_on:
      - database_ioasys

volumes:
  pgdata:
    driver: local